# This is a basic workflow to help you get started with Actions
# from Kade Engine github

name: Linux

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.4
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          sudo apt-get install vlc-bin
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib git hscript https://github.com/skuqre/hscript
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec 4351cf5b672da3e9379c88cbb07a386a681cbadc
          haxelib install flixel-addons
          haxelib install yaml
          haxelib install actuate
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list
          haxelib run lime build Project.xml linux 
          
      - uses: actions/upload-artifact@v2
        with:
          name: Linux Build
          path: export/release/linux/bin
